### ISSUE TITLE
Tcp Client Server Crash

### ISSUE THREAD

**Issue by Rezakarimi66** [Qihoo360/evpp#55]
Hi 
I have run my first test with your library. Its performance seems very good. But I have a problem with the size of packets. When I set the size of packet to 10000 or higher, I get a crash in Buffer class (std::bad_alloc). I have attached my code below. Should I set size of sending buffer manually?
[ClientServer.tar.gz](https://github.com/Qihoo360/evpp/files/1132830/ClientServer.tar.gz)

**Comment by zieckey** [comment]
Please paste the steps how to reproduce your problem. Suggestion as bellow
1. Open a github repo and upload your code
2. The steps how to compile it
3. The steps how to run it
4. And at last show me which line of the code crashes.

**Comment by Rezakarimi66** [comment]
Steps to reproduce my problem:
1- Untar the zip file that I have uploaded in the first message.
2- Build both projects (TCPServer and TCPClient) by CMake
3- Run TCPServer
4- Run TCPClient
5- Increase size of packet which is going to be sent in Line 23 of Client.cpp to 100000 and crash!!!

**Comment by Rezakarimi66** [comment]
@zieckey Are you able to reproduce my problem?

**Comment by zieckey** [comment]
```C++
            byteToSend.resize(100000);
            std::cout << "Size in Byte " << byteToSend.size() << std::endl;
            auto startClock = clock();
            while (count < 1000000)
            {
                conn->Send(byteToSend);
                count ++;
            }
            auto stopClock = clock();
```

The codes above will send 1000000 messages, and every message is 100000 size length.

TCPConn::Send(...) may not actually write the data to the socket fd, otherwise if the data is two large to send immediately, it will hold the data to a internal output buffer, and then when the socket fd is writable, TCPConn will write the data which is stored in the internal output buffer to the socket fd.

At this case, you send too many message in the same loop time, that will make the internal buffer can not   allocate enough memory to hold the data. So it crashes.

At the real world, all most it will be:
1. TCPClient sends a message to the server
2. TCPServer receives a message from the server
3. and so on

**Comment by Rezakarimi66** [comment]
@zieckey Thanks for your answer. Can we set a maximum value for the buffer size to prevent application crash and warn user about misconfiguration?

**Comment by zieckey** [comment]
You can use TCPConn::ReserveOutputBuffer to set a maximum value for the output buffer size, but can not prevent application crash, that only delay the crash time.

You can use TCPConn::SetHighWaterMarkCallback(...) to set a callback and when the output size increased to  the set value, the callback will be called.
